Repository team-gogo/gogo-minigame, pull requests merged in 2025-03, with the labels that each got.

#27 트랜잭션을 서비스로직에 관리하게 리펙터링
  domain/model/coin_toss_result.py
  domain/model/plinko_result.py
  domain/model/yavarwee_result.py
  presentation/schema/plinko.py
  service/cointoss.py
  service/plinko.py
Labels: enhancement

#29 [feat] 티켓 관련 로직 구현
  domain/repository/ticket.py
  presentation/cointoss.py
  presentation/plinko.py
  service/cointoss.py
  service/plinko.py
Labels: enhancement

#30 [feat] yavarwee 미니게임 구현
  .dev.env
  config.py
  domain/model/yavarwee_result.py
  domain/repository/yavarwee.py
  presentation/schema/yavarwee.py
  presentation/yavarwee.py
  server.py
  service/yavarwee.py
Labels: enhancement

#32 [feat] 활성화된 미니게임, 티켓 조회 api 구현
  domain/repository/ticket.py
  presentation/minigame.py
  presentation/schema/minigame.py
  presentation/schema/ticket.py
  presentation/ticket.py
  server.py
  service/minigame.py
  service/ticket.py
Labels: enhancement

#38 스테이지 생성 이벤트 consume 로직 구현
  event/consumer.py
  event/producer.py
  event/schema/fast.py
  event/schema/official.py
  event/schema/stage.py
  pyproject.toml
  server.py
  src/minigame/domain/model/minigame.py
  src/minigame/domain/repository/minigame.py
  src/minigame/presentation/schema/minigame.py
  src/minigame/service/impl/cointoss.py
  src/minigame/service/impl/plinko.py
  src/minigame/service/impl/yavarwee.py
  src/minigame/service/minigame.py
Labels: enhancement

#43 [feat] 티켓 이벤트 컨슘 구현
  event/consumer.py
  event/controller.py
  event/schema/ticket.py
  src/cointoss/domain/model/coin_toss_result.py
  src/minigame/domain/model/minigame.py
  src/plinko/domain/model/plinko_result.py
  src/ticket/domain/model/ticket.py
  src/ticket/domain/repository/ticket.py
  src/ticket/service/ticket.py
  src/yavarwee/domain/model/yavarwee_result.py
Labels: enhancement

#45 [fix] 공식 stage 생성 event schema 변경
  event/controller.py
  event/schema/fast.py
  event/schema/official.py
  src/minigame/domain/model/minigame.py
  src/minigame/presentation/schema/event.py
  src/minigame/presentation/schema/minigame.py
  src/minigame/service/minigame.py
Labels: bug

#53 [feat] 티켓 consume 실패 event 로직 추가
  event/consumer.py
  event/producer.py
  event/topic.py
  server.py
  src/cointoss/domain/model/coin_toss_result.py
  src/minigame/domain/model/minigame.py
  src/plinko/domain/model/plinko_result.py
  src/ticket/domain/model/ticket.py
  src/ticket/service/ticket.py
  src/yavarwee/domain/model/yavarwee_result.py
Labels: enhancement

#54 [feat] 스테이지 생성시 기본 티켓 갯수 로직 추가
  event/controller.py
  event/producer.py
  event/schema/fast.py
  src/cointoss/domain/model/coin_toss_result.py
  src/cointoss/presentation/controller/cointoss.py
  src/minigame/domain/model/minigame.py
  src/minigame/presentation/schema/event.py
  src/minigame/service/impl/cointoss.py
  src/minigame/service/impl/plinko.py
  src/minigame/service/impl/yavarwee.py
  src/minigame/service/minigame.py
  src/minigame/service/validation.py
  src/plinko/domain/model/plinko_result.py
  src/ticket/domain/model/ticket.py
  src/ticket/presentation/controller/ticket.py
  src/ticket/service/ticket.py
  src/yavarwee/domain/model/yavarwee_result.py
  src/yavarwee/domain/repository/yavarwee.py
  src/yavarwee/presentation/controller/yavarwee.py
Labels: enhancement

#64 [feat] 로그 포멧 변경
  db.py
  middleware.py
  server.py
Labels: enhancement

#67 [feat] CICD 구성
  .github/workflows/ci.yml
  .github/workflows/stage-cd.yml
  Dockerfile
  docker-compose.yml
  middleware.py
  server.py
  src/cointoss/domain/model/coin_toss_result.py
  src/minigame/domain/model/minigame.py
  src/minigame/service/impl/cointoss.py
  src/minigame/service/impl/plinko.py
  src/minigame/service/impl/yavarwee.py
  src/plinko/domain/model/plinko_result.py
  src/yavarwee/domain/model/yavarwee_result.py
Labels: enhancement

#69 [bug] 미들웨어 버그 수정
  middleware.py
Labels: bug

#71 [bug] 미니게임 버그 수정
  src/minigame/presentation/schema/event.py
  src/minigame/service/impl/cointoss.py
  src/minigame/service/impl/plinko.py
  src/minigame/service/impl/yavarwee.py
Labels: bug

#73 [bug] 스테이지 생성시 티켓 초기화 안되는 버그 수정
  event/schema/official.py
  src/minigame/domain/model/minigame.py
  src/minigame/service/minigame.py
Labels: bug

#77 [fix] 자신의 티켓이 조회되지 않는 버그 수정
  src/ticket/domain/model/ticket.py
  src/ticket/domain/repository/ticket.py
  src/ticket/service/ticket.py
Labels: bug

#81 미니게임 배팅시에 user_id로 포인트를 조회하는 버그 수정
  src/minigame/service/impl/cointoss.py
  src/minigame/service/impl/plinko.py
  src/minigame/service/impl/yavarwee.py
Labels: bug

#83 배팅 결과가 소숫점으로 계산시 500이 발생하는 에러 해결
  src/minigame/service/impl/cointoss.py
  src/minigame/service/impl/plinko.py
  src/minigame/service/impl/yavarwee.py
Labels: bug

#85 [bug] 미니게임 베팅 관련 minor 버그 수정
  .idea/dataSources.xml
  src/minigame/service/impl/cointoss.py
  src/minigame/service/impl/plinko.py
  src/minigame/service/impl/yavarwee.py
Labels: bug

#90 학생이 스테이지에 참여중인지 검사하는 로직 구현
  .idea/dataSources.xml
  src/minigame/presentation/controller/minigame.py
  src/minigame/service/impl/cointoss.py
  src/minigame/service/impl/plinko.py
  src/minigame/service/impl/yavarwee.py
  src/minigame/service/minigame.py
  src/minigame/service/validation.py
Labels: bug, enhancement

#88 최소 최대 배팅 포인트 검사 로직 구현
  src/minigame/service/impl/cointoss.py
  src/minigame/service/impl/plinko.py
  src/minigame/service/impl/yavarwee.py
Labels: bug, enhancement

#92 minigame status 키워드 통합
  src/minigame/domain/model/minigame.py
  src/minigame/service/minigame.py
Labels: enhancement
